In [4]:
import numpy as np

# 由 4-byte 整數所構成 2 維 2 x 3 矩陣
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [5]:
y = np.arange(35).reshape(5, 7)
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [6]:
print(y[1:5:2, :])

[[ 7  8  9 10 11 12 13]
 [21 22 23 24 25 26 27]]


In [7]:
print(y[1:5:2, ::3])

[[ 7 10 13]
 [21 24 27]]


In [8]:
z = np.arange(10, 1, -1)
print(z)

[10  9  8  7  6  5  4  3  2]


In [9]:
print(z[np.array([3, 3, -3, 8])])

[7 7 4 2]
